### ISSUE TITLE
Mobile Compatibility

### ISSUE THREAD

**Issue by ValerianClerc** [Compete-McGill/wisp-ui#21]
Clean up existing pages to look good on mobile devices (and on all ranges of screen sizes).

**Comment by MohamedBeydoun** [comment]
Main features that need to be fixed on small screens are:
* navbar: should become a drawer
* homepage buttons

**Comment by MohamedBeydoun** [comment]
881821bd268226bfbf63d8f7f0ccb5d9f59b7678
