### ISSUE TITLE
Search for problems

### ISSUE THREAD

**Issue by MohamedBeydoun** [Compete-McGill/wisp-ui#49]
Users should be able to search for issues in the problems index the same way they can search for problem sets.

**Comment by ValerianClerc** [comment]
Write the search functionality as a `mix-in`, so that we can reuse it in the Problems and Problemsets page

**Comment by MohamedBeydoun** [comment]
> Write the search functionality as a `mix-in`, so that we can reuse it in the Problems and Problemsets page

unfortunately, the search functions will be different enough to warrant not using mixins
